export default {
  'Cherkasy Oblast': 'Черкаська область',
  'Chernihiv Oblast': 'Чернігівська область',
  'Chernivtsi Oblast': 'Чернівецька область',
  'Crimea Republic*': 'Республіка Крим',
  'Dnipropetrovsk Oblast': 'Дніпропетровська область',
  'Donetsk Oblast': 'Донецька область',
  'Ivano-Frankivsk Oblast': 'Івано-Франківська область',
  'Kharkiv Oblast': 'Харківська область',
  'Kherson Oblast': 'Херсонська область',
  'Khmelnytskyi Oblast': 'Хмельницька область',
  'Kiev': 'Київ',
  'Kiev Oblast': 'Київська область',
  'Kirovohrad Oblast': 'Кіровоградська область',
  'Luhansk Oblast': 'Луганська область',
  'Lviv Oblast': 'Львівська область',
  'Mykolaiv Oblast': 'Миколаївська область',
  'Odessa Oblast': 'Одеська область',
  'Poltava Oblast': 'Полтавська область',
  'Rivne Oblast': 'Рівненська область',
  'Sevastopol*': 'Севастополь область',
  'Sumy Oblast': 'Сумська область',
  'Ternopil Oblast': 'Тернопільська область',
  'Vinnytsia Oblast': 'Вінницька область',
  'Volyn Oblast': 'Волинська область',
  'Zakarpattia Oblast': 'Закарпатська область',
  'Zaporizhia Oblast': 'Запорізька область',
  'Zhytomyr Oblast': 'Житомирська область',
}